site_name: FastAPI CacheKit
repo_url: https://github.com/devbijay/Fast-Cache
edit_uri: edit/main/docs/
repo_name: FastAPI CacheKit
site_url: https://devbijay.github.io/Fast-Cache
theme:
  name: material
  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - content.footnote.tooltips

  font:
    text: Roboto

  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Backends:
      - Overview: backends.md
      - In-Memory: backends/in_memory.md
      - Redis: backends/redis.md
      - Postgres: backends/postgres.md
      - Memcached: backends/memcached.md
      - MongoDB: backends/mongodb.md
      - FireStore: backends/firestore.md
  - API Reference: api.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/devbijay/Fast-Cache
      name: GitHub
  announcement:
    type: info
    text: "⭐️ Star FastAPI CacheKit on [GitHub](https://github.com/devbijay/Fast-Cache)!"
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

plugins:
  - search:
      lang: en
      separator: '[\s\-\.]+'
      pipeline:
        - stemmer
        - stopWordFilter
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google