site_name: FastAPI CacheKit
repo_url: https://github.com/devbijay/Fast-Cache
edit_uri: edit/main/docs/
repo_name: FastAPI CacheKit
site_url: https://devbijay.github.io/Fast-Cache
theme:
  name: material
  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.path
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.tracking
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - content.footnote.tooltips
    - toc.follow

  font:
    text: Roboto

  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Backends:
      - Overview: backends.md
      - In-Memory: backends/in_memory.md
      - Redis: backends/redis.md
      - Postgres: backends/postgres.md
      - Memcached: backends/memcached.md
      - MongoDB: backends/mongodb.md
      - FireStore: backends/firestore.md
      - DynamoDB: backends/dynamodb.md
  - API Reference: api.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/devbijay/Fast-Cache
      name: GitHub
  announcement:
    type: info
    text: "⭐️ Star FastAPI CacheKit on [GitHub](https://github.com/devbijay/Fast-Cache)!"
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

plugins:
  - search:
      lang: en
      separator: '[\s\-\.]+'
      pipeline:
        - stemmer
        - stopWordFilter
  - mkdocstrings:
      handlers:
        python:
          options:
            merge_init_into_class: true
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            separate_signature: true
            unwrap_annotated: true
            members_order: source
            preload_modules:
              - httpx
              - starlette
            docstring_style: google
            show_source: true
            show_signature: true
            show_root_heading: true
            show_inheritance_diagram: true
            show_if_no_docstring: true
            extra:
              follow_wrapped: true