site_name: FastAPI CacheKit
repo_url: https://github.com/devbijay/Fast-Cache
repo_name: FastAPI CacheKit
site_url: https://devbijay.github.io/Fast-Cache
theme:
  name: material
  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.instant

  font:
    text: Roboto

  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Backends:
      - Overview: backends.md
      - In-Memory: backends/in_memory.md
      - Redis: backends/redis.md
      - Postgres: backends/postgres.md
      - Memcached: backends/memcached.md
  - API Reference: api.md

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google